name: prapare
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.0
  fhir: ^0.2.4
  fhir_at_rest: ^0.2.5
  fhir_auth: ^0.2.1
  fhir_db: ^0.2.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^1.3.0
  flutter_sheet_localization: ^2.0.1
  flutter_svg: ^0.19.1
  freezed_annotation: ^0.12.0
  get: ^3.23.1
  get_storage: ^1.3.2
  http: ^0.12.2
  introduction_screen: ^1.0.9
  money2: ^2.0.2
  remote_state: ^1.5.0
  translator: ^0.1.5
  url_launcher: ^5.7.10
  validators: ^2.0.1

dev_dependencies:
  build_runner: ^1.10.2
  flutter_sheet_localization_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.2

# TODO: fix dependencies
dependency_overrides:
  analyzer: 0.41.2
  intl: ^0.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/fhir_servers/
    - assets/icons/
    - assets/icons/info/
    - assets/icons/survey_tab/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
